env:
  commonjs: true
  es6: true
  node: true
  mocha: true
extends: airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules: 
  "mocha/no-exclusive-tests": "error"
  "chai-friendly/no-unused-expressions": 2
  "no-unused-expressions": 0
  "no-underscore-dangle":  ["error", { "allow": ["__get__"] }]
plugins: 
  - mocha
  - chai-friendly
