version: '2.2'
services:
  gratibot:
    container_name: gratibot
    entrypoint: nodemon --watch service --watch skills bot.js 
    image: gratibot
    ports:
      - 3000:3000
    build: .
    environment:
      - debug
      - clientId
      - clientSecret
      - clientSigningSecret
      - emoji
      - exemptUsers
      - botHostname
    volumes:
      - .:/app
  mongodb:
    ports:
      - 27017:27017
    image: mongo:3.6
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
    driver: local
