apiVersion: skaffold/v1beta12
kind: Config
build:
  artifacts:
  - image: gratibot
    context: .
test:
- image: gratibot
  structureTests:
  - ./image-test/*
deploy:
  helm:
    flags:
    releases:
    - name: gratibot
      namespace: toolchain
      chartPath: charts/gratibot
      values:
        gratibot.image: gratibot
      setValueTemplates:
        domain: "{{.DOMAIN}}"
        mongodbUri: "gratibot-db/gratibot"
