{{ if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "{{ .Chart.Name }}"
spec:
  hosts:
  - gratibot.{{ .Values.domain }}
  gateways:
  - istio-system/app-gateway
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: gratibot
        port:
          number: 3000
{{ end }}