apiVersion: v1
kind: Service
metadata:
  name: gratibot
  labels:
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      name: gratibot
  selector:
      app: gratibot

