apiVersion: v1
kind: Service
metadata:
  name: gratibot
  labels:
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      name: http
  selector:
      app: gratibot
---
apiVersion: v1
kind: Service
metadata:
  name: gratibot-db
  labels:
      chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
      name: http
  selector:
      app: gratibot-db

